name: Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        # Pythonを設定するためのアクションのバージョン
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          # 省略可能 - x64 または x86 アーキテクチャ、既定値は x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python
        run: python sample.py